version: "2"
                   services:
                     web:
                       build: .
                       volumes:
                         - ./ :/app
                       ports:
                         - "4005:4005"
                       links:
                         - mongo
                     mongo:
                       image: mongo
                       ports:
                         - "3005:3005"