version: '3'
services:
  web:
    image: "docker-node-express-mongoapp"
    build: .
    command: node index.js
    ports:
      - "4005:4005"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"

    ports:
      - "3005:3005"
  adminmongo:
    image: "mrvautin/adminmongo"

    ports:
      - "1234:1234"