version: "2"
services:
  web:
    image: pcberriop/2b_awards
    volumes:
      - ./:/app
    ports:
      - "4005:4005"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "3005:3005"